# ==============================================================================
#  实验基本配置
# ==============================================================================
experiment:
  model_name: "bert-base-uncased"
  dataset_name: "imdb"
  task_type: "sequence_classification"

# ==============================================================================
#  PEFT方法配置（用于单次训练）
# ==============================================================================
peft:
  method: "lora"
  params:
    r: 16
    lora_alpha: 32
    lora_dropout: 0.1
    target_modules: ["q_proj", "v_proj"]

# ==============================================================================
#  训练超参数配置（用于单次训练）
# ==============================================================================
training:
  learning_rate: 5e-4
  batch_size: 16
  epochs: 3
  #weight_decay: 0.01

# ==============================================================================
#  Optuna超参数优化器配置
# ==============================================================================
tuner:
  direction: "minimize"  # 可选值："minimize"或"maximize"
  n_trials: 20  # 优化尝试次数
  study_name: "peft_optimization"  # 可选，用于持久化优化结果

# ==============================================================================
#  Optuna超参数搜索空间配置（用于超参数优化）
# ==============================================================================
search_space:
  # PEFT方法搜索空间
  peft:
    methods: ["lora", "ia3", "adalora"]  # 要搜索的PEFT方法
    
    # LoRA参数搜索范围
    lora:
      r:
        min: 4
        max: 64
        step: 4
      lora_alpha:
        min: 16
        max: 128
        step: 16
      lora_dropout:
        min: 0.05
        max: 0.3
    
    # AdaLoRA参数搜索范围
    adalora:
      r:
        min: 4
        max: 32
        step: 4
      target_r:
        min: 2
        max: 16
        step: 2
      lora_alpha:
        min: 16
        max: 64
        step: 16
  
  # 训练参数搜索空间
  training:
    learning_rate:
      min: 1e-5
      max: 1e-3
      log: true  # 对数尺度搜索
    batch_size:
      values: [8, 16, 32]  # 离散值
    epochs:
      min: 2
      max: 5
    weight_decay:
      min: 0.001
      max: 0.1
      log: true  # 对数尺度搜索 